PUT http://localhost:8089/workflow/auth/
Content-Type: application/json

{
  "user": "amorales"
}

###

GET http://localhost:8089/workflow/storage/version
Content-Type: application/json

###

PUT http://localhost:8089/workflow/storage/test
Content-Type: application/json

{
  "image": "imagen1",
  "clazzName": "la clase"
}

###

PUT http://localhost:8089/workflow/authenticate
Content-Type: application/json

{ "username": "javainuse",
"password": "password"
}

###

POST http://localhost:8089/workflow/storage/folder/Catálogos/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYXZhaW51c2UiLCJncm91cHMiOiJBQixDRCxFRixHIiwiR1JVUE9TIjoi77-9JmLvv71cdTAwMUbvv718We-_ve-_ve-_ve-_vVx1MDAwMu-_ve-_vWEiLCJleHAiOjE2MDYxODk0NzMsImlhdCI6MTYwNjE3MTQ3M30.8nTScyt56mX0Pjtlsg_rcvrQ-MnlhkrpwyPy7Ja_DymfFQZrdruDMQ-_Zp_MfZXlWLuzyUvJqdN6Bf8alAs6Jg

###

POST http://localhost:8089/workflow/storage/folder/Catálogos/Usuarios/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYXZhaW51c2UiLCJncm91cHMiOiJBQixDRCxFRixHIiwiR1JVUE9TIjoi77-9JmLvv71cdTAwMUbvv718We-_ve-_ve-_ve-_vVx1MDAwMu-_ve-_vWEiLCJleHAiOjE2MDYxODk0NzMsImlhdCI6MTYwNjE3MTQ3M30.8nTScyt56mX0Pjtlsg_rcvrQ-MnlhkrpwyPy7Ja_DymfFQZrdruDMQ-_Zp_MfZXlWLuzyUvJqdN6Bf8alAs6Jg

###

GET http://localhost:8089/workflow/storage/folder/Workflows/

###

POST http://localhost:8089/workflow/storage/folder/Workflows/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYXZhaW51c2UiLCJncm91cHMiOiJBQixDRCxFRixHIiwiR1JVUE9TIjoi77-9JmLvv71cdTAwMUbvv718We-_ve-_ve-_ve-_vVx1MDAwMu-_ve-_vWEiLCJleHAiOjE2MDYxODk0NzMsImlhdCI6MTYwNjE3MTQ3M30.8nTScyt56mX0Pjtlsg_rcvrQ-MnlhkrpwyPy7Ja_DymfFQZrdruDMQ-_Zp_MfZXlWLuzyUvJqdN6Bf8alAs6Jg

###

POST http://localhost:8089/workflow/storage/folder/Workflows/Seguimiento de Algo/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYXZhaW51c2UiLCJncm91cHMiOiJBQixDRCxFRixHIiwiR1JVUE9TIjoi77-9JmLvv71cdTAwMUbvv718We-_ve-_ve-_ve-_vVx1MDAwMu-_ve-_vWEiLCJleHAiOjE2MDYxODk0NzMsImlhdCI6MTYwNjE3MTQ3M30.8nTScyt56mX0Pjtlsg_rcvrQ-MnlhkrpwyPy7Ja_DymfFQZrdruDMQ-_Zp_MfZXlWLuzyUvJqdN6Bf8alAs6Jg

###

POST http://localhost:8089/workflow/storage/folder/Workflows/Seguimiento de Algo/Inicio/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYXZhaW51c2UiLCJncm91cHMiOiJBQixDRCxFRixHIiwiR1JVUE9TIjoi77-9JmLvv71cdTAwMUbvv718We-_ve-_ve-_ve-_vVx1MDAwMu-_ve-_vWEiLCJleHAiOjE2MDYxODk0NzMsImlhdCI6MTYwNjE3MTQ3M30.8nTScyt56mX0Pjtlsg_rcvrQ-MnlhkrpwyPy7Ja_DymfFQZrdruDMQ-_Zp_MfZXlWLuzyUvJqdN6Bf8alAs6Jg

###
POST http://localhost:8089/workflow/storage/folder/Workflows/Seguimiento de Algo/Autorización/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYXZhaW51c2UiLCJncm91cHMiOiJBQixDRCxFRixHIiwiR1JVUE9TIjoi77-9JmLvv71cdTAwMUbvv718We-_ve-_ve-_ve-_vVx1MDAwMu-_ve-_vWEiLCJleHAiOjE2MDYxODk0NzMsImlhdCI6MTYwNjE3MTQ3M30.8nTScyt56mX0Pjtlsg_rcvrQ-MnlhkrpwyPy7Ja_DymfFQZrdruDMQ-_Zp_MfZXlWLuzyUvJqdN6Bf8alAs6Jg

###
POST http://localhost:8089/workflow/storage/folder/Workflows/Seguimiento de Algo/Aceptadas/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYXZhaW51c2UiLCJncm91cHMiOiJBQixDRCxFRixHIiwiR1JVUE9TIjoi77-9JmLvv71cdTAwMUbvv718We-_ve-_ve-_ve-_vVx1MDAwMu-_ve-_vWEiLCJleHAiOjE2MDYxODk0NzMsImlhdCI6MTYwNjE3MTQ3M30.8nTScyt56mX0Pjtlsg_rcvrQ-MnlhkrpwyPy7Ja_DymfFQZrdruDMQ-_Zp_MfZXlWLuzyUvJqdN6Bf8alAs6Jg

###

POST http://localhost:8089/workflow/storage/folder/Workflows/Seguimiento de Algo/Rechazadas/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYXZhaW51c2UiLCJncm91cHMiOiJBQixDRCxFRixHIiwiR1JVUE9TIjoi77-9JmLvv71cdTAwMUbvv718We-_ve-_ve-_ve-_vVx1MDAwMu-_ve-_vWEiLCJleHAiOjE2MDYxODk0NzMsImlhdCI6MTYwNjE3MTQ3M30.8nTScyt56mX0Pjtlsg_rcvrQ-MnlhkrpwyPy7Ja_DymfFQZrdruDMQ-_Zp_MfZXlWLuzyUvJqdN6Bf8alAs6Jg

###

POST http://localhost:8089/workflow/storage/folder/Workflows/Seguimiento de Algo/Envio de Correo/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYXZhaW51c2UiLCJncm91cHMiOiJBQixDRCxFRixHIiwiR1JVUE9TIjoi77-9JmLvv71cdTAwMUbvv718We-_ve-_ve-_ve-_vVx1MDAwMu-_ve-_vWEiLCJleHAiOjE2MDYxODk0NzMsImlhdCI6MTYwNjE3MTQ3M30.8nTScyt56mX0Pjtlsg_rcvrQ-MnlhkrpwyPy7Ja_DymfFQZrdruDMQ-_Zp_MfZXlWLuzyUvJqdN6Bf8alAs6Jg

###

POST http://localhost:8089/workflow/storage/folder/Workflows/Alta de Accesos/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYXZhaW51c2UiLCJncm91cHMiOiJBQixDRCxFRixHIiwiR1JVUE9TIjoi77-9JmLvv71cdTAwMUbvv718We-_ve-_ve-_ve-_vVx1MDAwMu-_ve-_vWEiLCJleHAiOjE2MDYxODk0NzMsImlhdCI6MTYwNjE3MTQ3M30.8nTScyt56mX0Pjtlsg_rcvrQ-MnlhkrpwyPy7Ja_DymfFQZrdruDMQ-_Zp_MfZXlWLuzyUvJqdN6Bf8alAs6Jg

###

POST http://localhost:8089/workflow/storage/folder/Workflows/Alta de Accesos/Inicio/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYXZhaW51c2UiLCJncm91cHMiOiJBQixDRCxFRixHIiwiR1JVUE9TIjoi77-9JmLvv71cdTAwMUbvv718We-_ve-_ve-_ve-_vVx1MDAwMu-_ve-_vWEiLCJleHAiOjE2MDYxODk0NzMsImlhdCI6MTYwNjE3MTQ3M30.8nTScyt56mX0Pjtlsg_rcvrQ-MnlhkrpwyPy7Ja_DymfFQZrdruDMQ-_Zp_MfZXlWLuzyUvJqdN6Bf8alAs6Jg

###
POST http://localhost:8089/workflow/storage/folder/Workflows/Alta de Accesos/Autorización/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYXZhaW51c2UiLCJncm91cHMiOiJBQixDRCxFRixHIiwiR1JVUE9TIjoi77-9JmLvv71cdTAwMUbvv718We-_ve-_ve-_ve-_vVx1MDAwMu-_ve-_vWEiLCJleHAiOjE2MDYxODk0NzMsImlhdCI6MTYwNjE3MTQ3M30.8nTScyt56mX0Pjtlsg_rcvrQ-MnlhkrpwyPy7Ja_DymfFQZrdruDMQ-_Zp_MfZXlWLuzyUvJqdN6Bf8alAs6Jg

###
POST http://localhost:8089/workflow/storage/folder/Workflows/Alta de Accesos/Aceptadas/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYXZhaW51c2UiLCJncm91cHMiOiJBQixDRCxFRixHIiwiR1JVUE9TIjoi77-9JmLvv71cdTAwMUbvv718We-_ve-_ve-_ve-_vVx1MDAwMu-_ve-_vWEiLCJleHAiOjE2MDYxODk0NzMsImlhdCI6MTYwNjE3MTQ3M30.8nTScyt56mX0Pjtlsg_rcvrQ-MnlhkrpwyPy7Ja_DymfFQZrdruDMQ-_Zp_MfZXlWLuzyUvJqdN6Bf8alAs6Jg

###

POST http://localhost:8089/workflow/storage/folder/Workflows/Alta de Accesos/Rechazadas/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYXZhaW51c2UiLCJncm91cHMiOiJBQixDRCxFRixHIiwiR1JVUE9TIjoi77-9JmLvv71cdTAwMUbvv718We-_ve-_ve-_ve-_vVx1MDAwMu-_ve-_vWEiLCJleHAiOjE2MDYxODk0NzMsImlhdCI6MTYwNjE3MTQ3M30.8nTScyt56mX0Pjtlsg_rcvrQ-MnlhkrpwyPy7Ja_DymfFQZrdruDMQ-_Zp_MfZXlWLuzyUvJqdN6Bf8alAs6Jg

###

POST http://localhost:8089/workflow/storage/folder/Workflows/Alta de Accesos/Envio de Correo/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYXZhaW51c2UiLCJncm91cHMiOiJBQixDRCxFRixHIiwiR1JVUE9TIjoi77-9JmLvv71cdTAwMUbvv718We-_ve-_ve-_ve-_vVx1MDAwMu-_ve-_vWEiLCJleHAiOjE2MDYxODk0NzMsImlhdCI6MTYwNjE3MTQ3M30.8nTScyt56mX0Pjtlsg_rcvrQ-MnlhkrpwyPy7Ja_DymfFQZrdruDMQ-_Zp_MfZXlWLuzyUvJqdN6Bf8alAs6Jg

###


POST http://localhost:8089/workflow/storage/folder/Workflows/Demo 1/Solicitud Terminada/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYXZhaW51c2UiLCJncm91cHMiOiJBQixDRCxFRixHIiwiR1JVUE9TIjoi77-9JmLvv71cdTAwMUbvv718We-_ve-_ve-_ve-_vVx1MDAwMu-_ve-_vWEiLCJleHAiOjE2MDYxODk0NzMsImlhdCI6MTYwNjE3MTQ3M30.8nTScyt56mX0Pjtlsg_rcvrQ-MnlhkrpwyPy7Ja_DymfFQZrdruDMQ-_Zp_MfZXlWLuzyUvJqdN6Bf8alAs6Jg

###

POST http://localhost:8089/workflow/storage/upload/
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="persistence.xml"

// The 'input.txt' file will be uploaded
< C:/develop/persistence.xml
--boundary


###


GET http://localhost:8089/workflow/storage/download/3/ejemplo%2exml

###

###

PUT http://localhost:8089/workflow/commands/list/Workflows/
Content-Type: application/json
Authorization: token ZKZJ/alVw9gQ/mdfGbK5TXDlmajYcEth2hhtHBUXsIw+zLa5ZDm6x4fovB57qKu1Qe27b14nkjXlFUNksHAX4tKOJZkk05kHO/ncQTU0f/8jSPFnIVI1+C9Dqq9XIv06IRoVBxuGy7B4mHbRX/vJ23LNULCSPWRH2YMKm8U989A=

"ld"

###
